crits:
  sites:
    demo_central:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 300
        port: 444
        source: dsie
        ssl: true
        user: api
      host: 54.154.52.195
    demo_site_a:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 300
        port: 444
        source: dsie
        ssl: true
        user: api
      host: 54.154.28.239
    demo_site_b:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 300
        port: 444
        source: dsie
        ssl: true
        user: api
      host: 54.154.64.114
daemon:
  debug: false
  log: edgy_crits.log
  pid: edgy_crits.pid
edge:
  sites:
    demo_central:
      host: 54.154.52.195
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 300
        port: 443
        ssl: true
        user: api
        version: 1.1
    demo_site_a:
      host: 54.154.28.239
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 300
        port: 443
        ssl: true
        user: api
        version: 1.1
    demo_site_b:
      host: 54.154.64.114
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 300
        port: 443
        ssl: true
        user: api
        version: 1.1
state:
