crits:
  sites:
    localhost:                                             # site name
      host: 127.0.0.1                                      # site ip / fqdn
      enabled: true                                        # off switch
      api:
        user: api                                          # crits api user
        key: changeme                                      # crits api key
        port: 443                                          # tcp port
        poll_interval: 30                                  # poll interval (in seconds)
        max_results: 1000                                  # 1000 is currently a hard-wired limit in crits but this can be reduced
        path: /api/v1/                                     # crits api path
        source: dsie                                       # crits releasability flag
        ssl: true                                          # use ssl?
        allow_self_signed: true                            # self-signed certs probably won't validate
  datagen:
      indicator_count: 100                                 # default number of indicators for datagen
edge:
  sites:
    localhost:                                             # site name
      host: 127.0.0.1                                      # site ip / fqdn
      enabled: true                                        # off switch
      stix:
        xmlns_name: dsie                                   # xml namespace alias
        xmlns_url: http://www.dsie.net/                    # xml namespace url
      taxii:
        user: admin                                        # edge user
        pass: avalanche                                    # edge pass
        port: 443                                          # tcp port
        poll_interval: 30                                  # poll interval (in seconds)
        path: /taxii-data                                  # edge taxii endpoint
        collection: system.Default                         # taxii collection
        version: 1.1                                       # taxii version
        ssl: true                                          # use ssl?
        allow_self_signed: false                           # self-signed certs probably won't validate
  datagen:
      indicator_count: 100                                 # default number of indicators for datagen
daemon:
  app_path: /opt/soltra/edge/repository/adapters/crits     # full path to adapter
  debug: false                                             # run in debug mode?
  log:
    file: edgy_crits.log                                   # log name
    rotate_count: 10                                       # max logs to retain
    rotate_size: 1024000                                   # max logfile size (in bytes)
  pid: edgy_crits.pid                                      # daemon pid file
  working_dir: /opt/soltra/edge/repository/adapters/crits  # full path to daemon working directory
  mongo:
    host: localhost                                        # mongo ip or fqdn
    port: 27017                                            # mongo port
    user:                                                  # mongo user
    pass:                                                  # mongo pass
    db: inbox                                              # mongo database
    collection: adapters.crits                             # mongo collection
datagen:
  canonical_tlds: datagen_samples/crits-tlds.txt           # canonical tlds for datagen
  email_header_samples: datagen_samples/mail_headers.yaml  # spammy headers for datagen
  
