crits:
  datagen:
      indicator_count: 100
  sites:
    localhost:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 30
        port: 444
        source: dsie
        ssl: true
        user: api
      enabled: true
      host: 127.0.0.1
    rackspace_central:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 30
        port: 444
        source: dsie
        ssl: true
        user: api
      enabled: false
      host: 204.232.238.141
    vm_site_a:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 30
        port: 444
        source: dsie
        ssl: true
        user: api
      enabled: false
      host: 192.168.128.129
daemon:
  app_path: /opt/soltra/edge/repository/adapters/crits
  debug: false
  log:
    file: edgy_crits.log
    rotate_count: 10
    rotate_size: 1024000
  pid: edgy_crits.pid
  working_dir: /opt/soltra/edge/repository/adapters/crits
  mongo:
    host: localhost
    port: 27017
    user:
    pass:
    db: inbox
    collection: adapters.crits
datagen:
  canonical_tlds: datagen_samples/tlds-alpha-by-domain.txt
  email_header_samples: datagen_samples/mail_headers.yaml
edge:
  datagen:
      indicator_count: 100
  sites:
    localhost:
      enabled: true
      host: 127.0.0.1
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 30
        port: 443
        ssl: true
        user: api
        version: 1.1
    rackspace_central:
      enabled: false
      host: 204.232.238.141
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 30
        port: 443
        ssl: true
        user: api
        version: 1.1
    vm_site_a:
      enabled: false
      host: 192.168.128.129
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 30
        port: 443
        ssl: true
        user: api
        version: 1.1
