crits:
  sites:
    localhost:
      api:
        allow_self_signed: true
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        max_results: 1000
        path: /api/v1/
        poll_interval: 30
        port: 444
        source: dsie
        ssl: true
        user: api
      enabled: true
      host: 127.0.0.1
daemon:
  app_path: /opt/soltra/edge/repository/adapters/crits
  debug: true
  log:
    file: edgy_crits.log
    rotate_count: 10
    rotate_size: 1024000
  pid: edgy_crits.pid
  working_dir: /opt/soltra/edge/repository/adapters/crits
  mongo:
    host: localhost
    port: 27017
    user:
    pass:
    db: inbox
    collection: adapters.crits
edge:
  sites:
    localhost:
      enabled: true
      host: 127.0.0.1
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        allow_self_signed: true
        collection: system.Default
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        path: /taxii-data
        poll_interval: 30
        port: 443
        ssl: true
        user: api
        version: 1.1
state:
