crits:
  sites:
    central:
      host: 204.232.238.141
      enabled: true
      api:
        user: api
        key: 0055eaeb01c0f9f38cd65b190daf8f6d8e88c8fc
        port: 444
        poll_interval: 30
        max_results: 1000
        path: /api/v1/
        source: dsie
        ssl: true
        allow_self_signed: true
  datagen:
      indicator_count: 100
edge:
  sites:
    central:
      host: 204.232.238.141
      enabled: true
      stix:
        xmlns_name: dsie
        xmlns_url: http://www.dsie.net/
      taxii:
        user: api
        pass: Opiningbiddyproxywandzigzagsetchedeightjimmies_2347
        port: 443
        poll_interval: 30
        path: /taxii-data
        collection: system.Default
        version: 1.1
        ssl: true
        allow_self_signed: true
  datagen:
      indicator_count: 100
daemon:
  app_path: /opt/soltra/edge/repository/adapters/crits
  debug: false
  log:
    file: edgy_crits.log
    rotate_count: 10
    rotate_size: 1024000
  pid: edgy_crits.pid
  working_dir: /opt/soltra/edge/repository/adapters/crits
  mongo:
    host: localhost
    port: 27017
    user:
    pass:
    db: inbox
    collection: adapters.crits
datagen:
  canonical_tlds: datagen_samples/tlds-alpha-by-domain.txt
  email_header_samples: datagen_samples/mail_headers.yaml
  
